### ISSUE TITLE
Donner plus d'information sur comment installer le project

### ISSUE THREAD

**Issue by guillaume-gomez** [ProjectWasteland/api-test#1]
@BastienDuplessier, le build n'est pas aussi simple que ca. Il faudrait trouver le moyen d'automatiser le build et le documenter si nécessaire.

**Comment by BastienDuplessier** [comment]
Je suis d'accord.
Je vais écrire un truc dans le wiki pour installer tout ça.
Je le testerais sur une machine virtuelle.

**Comment by guillaume-gomez** [comment]
Done 👍
